version: '3.4'

services:
  ui-service:
    build:
        context: .
        dockerfile: UserInterface/Dockerfile
    depends_on:
        - collector-service
        - calculator-service
    ports:
        - "8000:80"
    restart:
        on-failure
        
  collector-service:
    build:
      context: .
      dockerfile: Collector/Dockerfile
    deploy:
      replicas: 2
    restart:
      on-failure
      
  calculator-service:
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    deploy:
      replicas: 2
    restart:
      on-failure

