version: '3.4'

services:
  collector-service:
    build:
      context: .
      dockerfile: Collector/Dockerfile
    deploy:
      replicas: 2
    restart:
      on-failure
      
  calculator-service:
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    deploy:
      replicas: 2
    ports:
       - "8000:80"
    restart:
      on-failure

